#[path = "aptos.rs"]
pub mod aptos;
#[path = "btc.rs"]
pub mod btc;
#[path = "eth.rs"]
pub mod eth;
#[path = "icp.rs"]
pub mod icp;
#[path = "near.rs"]
pub mod near;
#[path = "sepolia.rs"]
pub mod sepolia;
#[path = "sol.rs"]
pub mod sol;
#[path = "solana_testnet.rs"]
pub mod solana_testnet;
#[path = "sui.rs"]
pub mod sui;
#[path = "ton.rs"]
pub mod ton;
#[path = "trx.rs"]
pub mod trx;
