#[path = "aptos_mainnet.rs"]
pub mod aptos_mainnet;
#[path = "bitcoin.rs"]
pub mod bitcoin;
#[path = "ethereum.rs"]
pub mod ethereum;
#[path = "internet_computer.rs"]
pub mod internet_computer;
#[path = "near_mainnet.rs"]
pub mod near_mainnet;
#[path = "sepolia.rs"]
pub mod sepolia;
#[path = "solana.rs"]
pub mod solana;
#[path = "solana_testnet.rs"]
pub mod solana_testnet;
#[path = "sui_mainnet.rs"]
pub mod sui_mainnet;
#[path = "ton_mainnet.rs"]
pub mod ton_mainnet;
#[path = "tron.rs"]
pub mod tron;
